version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - elasticsearch

  # user-service-api:
  #   image: userserviceapi
  #   build:
  #     context: .\src\UserService\
  #     dockerfile: \UserService.Api\Dockerfile
  #   environment:
  #     ASPNETCORE_URLS: "https://+:5001"
  #   ports:
  #     - 5000:80
  #     - 5001:443
  #   links:
  #     - elasticsearch